# Generated by Django 5.0.1 on 2024-02-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0003_alter_anything_anything_alter_anything_something'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anything',
            old_name='anything',
            new_name='everything',
        ),
    ]
