# Generated by Django 5.0.1 on 2024-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0007_alter_note_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
