# Generated by Django 5.0.1 on 2024-02-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0008_alter_note_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
    ]
